sudo: false
language: go
go:
  - "1.12.x"

env:
  - GO111MODULE=on

before_script:
  - make get-build-deps

script:
  - make build

after_success:
 - curl --request POST "https://goreportcard.com/checks" --data "repo=github.com/skaeladmin/dfmanager"
 - bash <(curl -s https://codecov.io/bash)
# - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
